In [1]:
#1. Convert List to 1D Array

import numpy as np 

l=[12.23, 13.32, 100, 36.32]

x=np.array(l)

print(x)

[ 12.23  13.32 100.    36.32]


In [3]:
#2. Create 3x3 Matrix

import numpy as np 

x=np.arange(2,11).reshape(3,3)

print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
#3. Null Vector (10) & Update Sixth Value 

import numpy as np 

x=np.zeros(10)
print(x)

x[6]=11

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [7]:
#4. Array from 12 to 38

import numpy as np 

x=np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [8]:
#5. Convert Array to Float Type 

import numpy as np 

a=[1,2,3,4]

x=np.asarray(a, dtype=float)

print(x)

[1. 2. 3. 4.]


In [12]:
#6. Celsius to Fahrenheit Conversion

import numpy as np 

fvalues=[0, 12, 45.21, 34, 99.91]

F=np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)

print("Values in  Centigrade degrees:")
print(np.round((5*F/ 9- 5* 32/ 9), 2))

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73]


In [13]:
#7. Append Values to Array

import numpy as np 

x=[10,20,30]

x=np.append(x, [[40,50,60], [70,80,90]])

print(x)

[10 20 30 40 50 60 70 80 90]


In [15]:
#8. Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

import numpy as np 

random_array=np.random.rand(10)
print(f'Random array: {random_array}')

mean_value=np.mean(random_array)
print(f'Mean: {mean_value}')

median_value=np.median(random_array)
print(f'Median:{median_value}')

std_value=np.std(random_array)
print(f'STD: {std_value}')


Random array: [0.61646943 0.5746858  0.70140909 0.69792486 0.33101982 0.24760552
 0.14724362 0.94428874 0.92911677 0.29316568]
Mean: 0.5482929315188707
Median:0.5955776152322683
STD: 0.26768813302384814


In [16]:
#9. Create a 10x10 array with random values and find the minimum and maximum values 

import numpy as np 

arr=np.random.rand(10, 10)

min_val=np.min(arr)
max_val=np.max(arr)

print('Random 10x10 array:\n', arr)
print('\nMin value:', min_val)
print('Max value:', max_val)

Random 10x10 array:
 [[0.22736179 0.23220002 0.20883215 0.58792936 0.42643226 0.2705611
  0.82287083 0.70277532 0.01372379 0.39424113]
 [0.43880665 0.05608622 0.54667553 0.96384215 0.48867463 0.10348439
  0.29863564 0.30451673 0.77814057 0.27810905]
 [0.64543537 0.43162492 0.66779157 0.63986985 0.75413938 0.35313948
  0.12840104 0.70985236 0.01996593 0.03886073]
 [0.44899438 0.92853541 0.41435822 0.15068352 0.86794842 0.05070213
  0.37366928 0.0757885  0.24050793 0.86569836]
 [0.13267878 0.20288171 0.08179951 0.98567444 0.68788907 0.54372985
  0.32467359 0.45398916 0.35116387 0.78560149]
 [0.55928916 0.30687521 0.14508636 0.72209715 0.18024703 0.85879475
  0.59628097 0.19369864 0.67222947 0.359357  ]
 [0.12942704 0.22108929 0.63668455 0.22983731 0.63959786 0.04919286
  0.91290561 0.60939484 0.23474311 0.69504708]
 [0.43916938 0.46921569 0.49603474 0.97125482 0.74814515 0.81415422
  0.34530552 0.00733398 0.57879135 0.71512871]
 [0.71075758 0.82729316 0.23882699 0.52565803 0.91150795 0.2

In [17]:
#10. Create a 3x3x3 array with random values.

import numpy as np 

arr=np.random.rand(3,3,3)

print('3x3x3 Random Array:\n', arr)

3x3x3 Random Array:
 [[[0.10408033 0.9995792  0.79554011]
  [0.61843312 0.52889155 0.15963715]
  [0.29387843 0.34328676 0.39956987]]

 [[0.28224493 0.32839336 0.50908536]
  [0.51861955 0.63738617 0.14488642]
  [0.09017504 0.02312385 0.98792993]]

 [[0.84940002 0.67365902 0.84566399]
  [0.29955543 0.58188495 0.8756576 ]
  [0.68849045 0.74202888 0.78683641]]]
